name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List build directory
        run: ls -la build/home

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DEPLOY_GHP_TEST }}
          publish_dir: build/home
          enable_jekyll: true