name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --prefix src -- --output-path=src/build/home

      - name: List build directory
        run: ls -la src/build/home

      - name: Verify build directory
        run: ls -R src/build/home

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.TOKEN_DEPLOY_TEST_GHP }}
          publish_branch: gh-pages  # Ensure this is set to gh-pages
          publish_dir: src/build/home  # Adjust this if your build directory is different
          enable_jekyll: true
          exclude_assets: .github  # Exclude hidden files and directories