name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build -- --output-path=dist/angular-github-actions --configuration production  # Ensure correct output path

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'github-pages'  # Ensure the artifact name matches
        path: 'dist/angular-github-actions'
        if-no-files-found: 'error'
